name: printer_two
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  flutter_svg: ^2.1.0
  go_router: ^15.1.2
  connectivity_plus: ^6.1.4
  smooth_page_indicator: ^1.2.1
  flutter_inappwebview: ^6.1.5
  file_picker: ^10.1.9
  pdf: ^3.11.3
  share_plus: ^10.1.4
  path_provider: ^2.1.5
  permission_handler: ^11.2.1
  url_launcher: ^6.3.1
  photo_manager: ^3.6.4
  printing: ^5.14.2
  screenshot: ^3.0.0
  google_mlkit_text_recognition: ^0.15.0
  cunning_document_scanner: ^1.2.3
  # firebase_core: ^3.13.1
  # cloud_firestore: ^5.6.8
  purchases_flutter: ^8.8.1
  purchases_ui_flutter: ^8.8.1
  # in_app_review: ^2.0.10
  # receive_sharing_intent: ^1.8.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
      - assets/
      - assets/fonts/
  fonts:
    - family: w400
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: w500
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: w600
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
    - family: w700
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
